# Generated by Django 4.2.7 on 2023-11-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default="", max_length=255)),
                ("fname", models.CharField(default="", max_length=255)),
                ("lname", models.CharField(default="", max_length=255)),
                ("age", models.IntegerField(default=0)),
                ("country", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
                ("school", models.CharField(default="", max_length=255)),
                ("grad_m", models.CharField(default="", max_length=255)),
                ("grad_y", models.CharField(default="", max_length=255)),
                ("budget", models.IntegerField(default=0)),
                ("gpa", models.CharField(default="", max_length=255)),
                ("utr", models.CharField(default="", max_length=255)),
                ("utr_link", models.URLField(default="", max_length=255)),
                ("uni_name", models.CharField(default="", max_length=255)),
                ("coach_email", models.EmailField(default="", max_length=255)),
                ("uni_region", models.CharField(default="", max_length=255)),
                ("uni_wtn", models.CharField(default="", max_length=255)),
                ("uni_team", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("logo", models.CharField(default="", max_length=1000)),
                ("team", models.CharField(default="", max_length=1000)),
                ("division", models.CharField(default="", max_length=255)),
                ("conference", models.CharField(default="", max_length=255)),
                ("region", models.CharField(default="", max_length=255)),
                ("wtn", models.CharField(default="", max_length=255)),
                ("coach_name", models.CharField(default="", max_length=255)),
                ("coach_email", models.EmailField(default="", max_length=255)),
            ],
        ),
    ]
